<?php

use think\migration\Seeder;

class Permissions extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'name' => '权限管理',
                'icon' => 'fa fa-calendar-o',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 2,
                'name' => '用户管理',
                'icon' => '',
                'pid' => 1,
                'module' => 'admin',
                'controller' => 'user',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 3,
                'name' => '角色管理',
                'icon' => '',
                'pid' => 1,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 4,
                'name' => '菜单管理',
                'icon' => '',
                'pid' => 1,
                'module' => 'admin',
                'controller' => 'permission',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 5,
                'name' => '创建用户',
                'icon' => '',
                'pid' => 2,
                'module' => 'admin',
                'controller' => 'user',
                'action' => 'create',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 6,
                'name' => '编辑用户',
                'icon' => '',
                'pid' => 2,
                'module' => 'admin',
                'controller' => 'user',
                'action' => 'edit',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 7,
                'name' => '删除用户',
                'icon' => '',
                'pid' => 2,
                'module' => 'admin',
                'controller' => 'user',
                'action' => 'delete',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 8,
                'name' => '创建角色',
                'icon' => '',
                'pid' => 3,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'create',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 9,
                'name' => '编辑角色',
                'icon' => '',
                'pid' => 3,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'edit',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 10,
                'name' => '删除角色',
                'icon' => '',
                'pid' => 3,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'delete',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 11,
                'name' => '获取角色权限',
                'icon' => '',
                'pid' => 3,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'getPermissionsOfRole',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 12,
                'name' => '分配权限',
                'icon' => '',
                'pid' => 3,
                'module' => 'admin',
                'controller' => 'role',
                'action' => 'givePermissions',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 13,
                'name' => '分配角色',
                'icon' => '',
                'pid' => 2,
                'module' => 'admin',
                'controller' => 'user',
                'action' => 'giveRoles',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 14,
                'name' => '创建菜单',
                'icon' => '',
                'pid' => 4,
                'module' => 'admin',
                'controller' => 'permission',
                'action' => 'create',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 15,
                'name' => '编辑菜单',
                'icon' => '',
                'pid' => 4,
                'module' => 'admin',
                'controller' => 'permission',
                'action' => 'edit',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 16,
                'name' => '删除菜单',
                'icon' => '',
                'pid' => 4,
                'module' => 'admin',
                'controller' => 'permission',
                'action' => 'delete',
                'is_show' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

            [
                'id' => 17,
                'name' => '日志记录',
                'icon' => '',
                'pid' => 1,
                'module' => 'admin',
                'controller' => 'Log',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name' => '门店管理',
                'icon' => 'fa fa-bank',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'name' => '代理点管理',
                'icon' => 'fa fa-calendar-o',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'name' => '财务管理',
                'icon' => 'fa fa-money',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'name' => '系统设置',
                'icon' => 'fa fa-wrench',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'name' => '小程序设置',
                'icon' => 'fa fa-cog',
                'pid' => 0,
                'module' => '',
                'controller' => '',
                'action' => '',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'name' => '行业分类设置',
                'icon' => '',
                'pid' => 23,
                'module' => 'admin',
                'controller' => 'IndustryCategorySettings',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'name' => '新增行业',
                'icon' => '',
                'pid' => 25,
                'module' => 'admin',
                'controller' => 'IndustryCategorySettings',
                'action' => 'create',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'name' => '删除行业分类',
                'icon' => '',
                'pid' => 25,
                'module' => 'admin',
                'controller' => 'IndustryCategorySettings',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'name' => '编辑行业分类',
                'icon' => '',
                'pid' => 25,
                'module' => 'admin',
                'controller' => 'IndustryCategorySettings',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'name' => '基本信息',
                'icon' => '',
                'pid' => 24,
                'module' => 'admin',
                'controller' => 'wechatConfig',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'name' => '基本设置',
                'icon' => '',
                'pid' => 23,
                'module' => 'admin',
                'controller' => 'config',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'name' => '充值积分设置',
                'icon' => '',
                'pid' => 23,
                'module' => 'admin',
                'controller' => 'IntegralPackage',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'name' => '新建积分充值套餐',
                'icon' => '',
                'pid' => 31,
                'module' => 'admin',
                'controller' => 'IntegralPackage',
                'action' => 'create',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'name' => '编辑积分充值套餐',
                'icon' => '',
                'pid' => 31,
                'module' => 'admin',
                'controller' => 'IntegralPackage',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'name' => '删除积分充值套餐',
                'icon' => '',
                'pid' => 31,
                'module' => 'admin',
                'controller' => 'IntegralPackage',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'name' => '门店列表',
                'icon' => '',
                'pid' => 18,
                'module' => 'admin',
                'controller' => 'StoreManage',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'name' => '门店编辑',
                'icon' => '',
                'pid' => 35,
                'module' => 'admin',
                'controller' => 'StoreManage',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'name' => '入驻审核',
                'icon' => '',
                'pid' => 18,
                'module' => 'admin',
                'controller' => 'StoreExamine',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'name' => '卡券管理',
                'icon' => '',
                'pid' => 18,
                'module' => 'admin',
                'controller' => 'CouponManage',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'name' => '卡券编辑',
                'icon' => '',
                'pid' => 38,
                'module' => 'admin',
                'controller' => 'CouponManage',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'name' => '轮播图管理',
                'icon' => '',
                'pid' => 18,
                'module' => 'admin',
                'controller' => 'Banner',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'name' => '轮播图新增',
                'icon' => '',
                'pid' => 41,
                'module' => 'admin',
                'controller' => 'Banner',
                'action' => 'create',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'name' => '轮播图修改',
                'icon' => '',
                'pid' => 41,
                'module' => 'admin',
                'controller' => 'Banner',
                'action' => 'update',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'name' => '轮播图删除',
                'icon' => '',
                'pid' => 41,
                'module' => 'admin',
                'controller' => 'Banner',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'name' => '帮助中心',
                'icon' => '',
                'pid' => 24,
                'module' => 'admin',
                'controller' => 'HelpCenter',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'name' => '新增帮助',
                'icon' => '',
                'pid' => 47,
                'module' => 'admin',
                'controller' => 'HelpCenter',
                'action' => 'create',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'name' => '代理列表',
                'icon' => '',
                'pid' => 19,
                'module' => 'admin',
                'controller' => 'Agent',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'name' => '新增代理',
                'icon' => '',
                'pid' => 19,
                'module' => 'admin',
                'controller' => 'Agent',
                'action' => 'create',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'name' => '修改代理',
                'icon' => '',
                'pid' => 49,
                'module' => 'admin',
                'controller' => 'Agent',
                'action' => 'update',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'name' => '删除代理',
                'icon' => '',
                'pid' => 49,
                'module' => 'admin',
                'controller' => 'Agent',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'name' => '编辑模板',
                'icon' => '',
                'pid' => 42,
                'module' => 'admin',
                'controller' => 'Template',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'name' => '编辑帮助',
                'icon' => '',
                'pid' => 47,
                'module' => 'admin',
                'controller' => 'HelpCenter',
                'action' => 'edit',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'name' => '删除帮助',
                'icon' => '',
                'pid' => 47,
                'module' => 'admin',
                'controller' => 'HelpCenter',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'name' => '删除模板',
                'icon' => '',
                'pid' => 42,
                'module' => 'admin',
                'controller' => 'Template',
                'action' => 'delete',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'name' => '意见反馈',
                'icon' => '',
                'pid' => 23,
                'module' => 'admin',
                'controller' => 'Feedback',
                'action' => 'index',
                'is_show' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

        ];

        $this->table(config('permissions.table.permission'))->insert($data)->save();


    }
}