<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'thinking\\socialite\\' => array($baseDir . '/extend/socialite/src'),
    'thinking\\icloud\\' => array($baseDir . '/extend/icloud/src'),
    'think\\permissions\\' => array($vendorDir . '/wyw/permission/src'),
    'think\\migration\\' => array($vendorDir . '/topthink/think-migration/src'),
    'think\\composer\\' => array($vendorDir . '/topthink/think-installer/src'),
    'think\\captcha\\' => array($vendorDir . '/topthink/think-captcha/src'),
    'app\\' => array($baseDir . '/application'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'Phinx\\' => array($vendorDir . '/topthink/think-migration/phinx/src/Phinx'),
    'GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
);
